### ISSUE TITLE
Per World Config

### ISSUE THREAD

**Issue by jules552** [trentech/StackBan#1]
Hey,

Can you add the possibility to have "a per world config"?

Thank you for your work :)

**Comment by trentech** [comment]
623e4240573de6b59a10a38d86653fbe5f861fbf

**Comment by trentech** [comment]
Multi-World support added to latest release. Also adds a global config to continue to allow server wide bans. Commands now require and world argument, substituting world for global when needed

Examples:
/sban set global minecraft:stone
/sban set world minecraft:stone
