### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by Whazaaaaa** [trentech/StackBan#11]
Hai im getting alot of console spam from the plugin anything I can do about it?

`10.02 19:39:45 [Server] Server thread/INFO [STDOUT]: [com.gmail.trentech.stackban.EventListener:onDropItemEvent:206]: DROP`

That x10 every second or so.

Thanks for the plugin.

**Comment by trentech** [comment]
OH hey that's a good thing. That means an event that wasn't implemented in Sponge is now working. Also means I need to update it to fix the spam. Thanks for the report

**Comment by Whazaaaaa** [comment]
Any ETA on the update? Or is it possible to get a small (hotfix)? I assume its basically only a few lines of code that need changing.

**Comment by Orcinuss** [comment]
Could we get an update for this. Its really annoying

**Comment by EvilCh33z** [comment]
update?

**Comment by fcpwiz** [comment]
I believe he fixed this here: https://github.com/trentech/StackBan/commit/b831166002c114ae54b4b04305a96a2132dcb48a

And you can get the new file here: https://github.com/trentech/StackBan/releases/tag/0.3.0

**Comment by trentech** [comment]
Yeah this has been resolved

**Comment by fcpwiz** [comment]
@trentech Quick question: does StackBan-v0.3.0 work on a 1.10.2 SpongeForge server?

**Comment by trentech** [comment]
I believe I built the release on API 5.2.0 although I don't remember anything really changing between 5.2.0 and 7.0.0 so it should work regardless

**Comment by fcpwiz** [comment]
Well, the name of the file (stackban-6.1.0-0.3.0.jar) does contain "6.1.0." So that'll work on a 5.2.0 server?

**Comment by trentech** [comment]
Like I said I don't think anything changed API wise so yes it should work

**Comment by fcpwiz** [comment]
Great, thanks!

**Comment by fcpwiz** [comment]
And which version of ProjectCore should I be using on my 5.2.0 server? I'm assuming the 5.2.0 one.
<img width="1016" alt="releases_ _trentech_projectcore" src="https://user-images.githubusercontent.com/2921172/27512177-f98a5b24-5905-11e7-8f64-7f0317081a6e.png">

**Comment by trentech** [comment]
Technically they're both the same but as to avoid comments about not having a version for 5.2.0 I created a build for both 6.x and 5.x. Doesn't really matter which one you use but it's always good practice to match 6.1.0 to 6.1.0 in case anything ever does change between versions

**Comment by fcpwiz** [comment]
Alright, thank you!
