### ISSUE TITLE
Duplication Glitch using banned items

### ISSUE THREAD

**Issue by DrZoddiak** [trentech/StackBan#14]
Version - 0.2.5
SF version - 2264

If you craft a banned item using a modded workbench. (i.e Tinkers Workbench) and then proceed to take said item and put it over any item you wish, it will duplicate the item and delete the banned item.

I know this is a duplicate of the issue labeled "BUG" but I figured this was more legible.

**Comment by trentech** [comment]
I beleive the latest dev build is backword compatible with API 5.x. Try it and see if the problem still occurs

**Comment by trentech** [comment]
https://trentech.org/jenkins/job/Stack%20Ban/

**Comment by pyscho974** [comment]
link seems dead..  is there still a version that works with api 5?

**Comment by DrZoddiak** [comment]
@pyscho974 I highly reccomend picking up a different banning plugin for api 5/6.
Griefprevention will work as well MMCRestrict will, I'm certain there are others out there.
This project is slow to update, and apparently decided API5 didn't need to exist.

I'll close this issue since API 5 doesn't exist and supposedly you fixed the issue. If you didn't test it up to this point that's it's you're issue now :)

**Comment by pyscho974** [comment]
thanks for the reply..  im using nations plugin so not sure if griefprevention work with it..  need to be able to ban items to set dimensions tho like automining machines to mining world only.
