### ISSUE TITLE
Update to API 6?

### ISSUE THREAD

**Issue by ghost** [trentech/StackBan#5]
Hi Sir!
But I'm sorry sir! I don't know what's the difference between API 5 and 6...

This plugin is very important for me, please be sure to keep it updated!
The server must need this kind of plug-in, otherwise, it is dangerous (for example, some Mod items).

**Comment by trentech** [comment]
This plugin is API compatible

**Comment by trentech** [comment]
I mean API 6.0.0

**Comment by ghost** [comment]
Thanks sir!
