### ISSUE TITLE
Question~since there is so little documentation

### ISSUE THREAD

**Issue by JohnPark234** [trentech/StackBan#6]
using stackban 5.0.0-0.2.3
does it support modded items/blocks
is it possible to add item/block ids with meta data? (ie 5208:82)

**Comment by trentech** [comment]
Yes mod items and item meta(unsafe damage values) are supported. ie: modid:itemid:meta. For example minecraft:wool:3 for light blue wool. You can find out item ids using tab completion. 

/sban set <world> 

followed by hitting tab key lists all items available

**Comment by JohnPark234** [comment]
well i found the tab function to be quite helpful but it seems thats it not fully functional yet

So I selected a IC2 (Industrial Craft 2) chunkloader when using sb whatsthis i get: ic2:te:82
https://puu.sh/se9vg/af92da2462.png

so i get to the point where ive tabbed myself to the point of finding ic2:te by using the tab function
https://puu.sh/se9FV/e0eda0b476.png

but when it put ic2:te:82 i get the error No value present
https://puu.sh/se9Nu/2cc54f0272.png

so i tried just ic2:te... again no value present

so i looked at the server and got this error:
http://pastebin.com/XqVSx8tj

any help would be appreciated

**Comment by trentech** [comment]
Seems you found a bug I missed

**Comment by trentech** [comment]
Resolved

c3cf2f9616443fcec197f24270248fd0ecdbde08

**Comment by JohnPark234** [comment]
<3
